apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: import-github-issues-cron-job
spec:
  data: 'TODO'
  schedule: '* 0 * * *' # every minute
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: import-github-issues-channel
