apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: import-github-issues-log-sink
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: import-github-issues-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: log-sink
